import Navbar from './components/Navbar/Navbar';
import './global.css';

export const metadata = {
  title: 'Witek Rychlik | web dev',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-950 main-font">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
